### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.

### ISSUE THREAD

**Issue by doctordubba** [Zusier/Discord-Nitro-Sniper#4]
I definitely added the proper token in the proper location. I have used the same token with 10 other applications so I know it works and I'm putting it in the proper location. I'm not sure why this error is occur.

![image](https://user-images.githubusercontent.com/28602877/90328376-c5f88e00-df50-11ea-8605-578d1323bda4.png)

**Comment by Zusier** [comment]
did you put it in config.json or index.js?

**Comment by Zusier** [comment]
ok, after testing I am also getting this error, this is probably due to discord.js, making a downgrade pull request which should fix the issue.

**Comment by Zusier** [comment]
if you clone the repo again, run `npm i` twice and it should work again

**Comment by doctordubba** [comment]
Seems like it is resolved. Good Job!
